import type {Metadata} from "next";
import "./globals.css";
import {MainLayout} from "@/layouts/main-layout.tsx";
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <MainLayout>
            {children}
        </MainLayout>
    );
}
